/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package encryptAndDecrypt;

/**
 *
 * @author pehor9164
 */
public class encryptAndDecrypt extends javax.swing.JFrame {

    /**
     * Creates new form encryptAndDecrypt
     */
    
    public encryptAndDecrypt() {
        initComponents();
        errorLbl.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPnl = new javax.swing.JPanel();
        decryptOutPutLbl = new javax.swing.JLabel();
        encryptOutPutTxtFeild = new javax.swing.JTextField();
        encryptOutputLbl = new javax.swing.JLabel();
        decryptOutPutTxtFeild = new javax.swing.JTextField();
        decryptBtn = new javax.swing.JButton();
        encryptLbl = new javax.swing.JLabel();
        encryptTxtFeild = new javax.swing.JTextField();
        titleLbl = new javax.swing.JLabel();
        encryptBtn = new javax.swing.JButton();
        decryptLbl = new javax.swing.JLabel();
        decryptTxtFeild = new javax.swing.JTextField();
        errorLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPnl.setBackground(new java.awt.Color(0, 255, 255));
        backgroundPnl.setForeground(new java.awt.Color(0, 102, 51));
        backgroundPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        decryptOutPutLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        decryptOutPutLbl.setText("Decrypted Message:");
        backgroundPnl.add(decryptOutPutLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        backgroundPnl.add(encryptOutPutTxtFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 380, -1));

        encryptOutputLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        encryptOutputLbl.setText("Encrypted Message:");
        backgroundPnl.add(encryptOutputLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        backgroundPnl.add(decryptOutPutTxtFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 380, -1));

        decryptBtn.setText("Decrypt");
        decryptBtn.setBorderPainted(false);
        decryptBtn.setFocusPainted(false);
        decryptBtn.setOpaque(false);
        decryptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(decryptBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        encryptLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        encryptLbl.setText("Enter A Message To Encyrpt:");
        backgroundPnl.add(encryptLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));
        backgroundPnl.add(encryptTxtFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 380, -1));

        titleLbl.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titleLbl.setText("Peter's Encryption Software");
        backgroundPnl.add(titleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        encryptBtn.setText("Encrypt");
        encryptBtn.setOpaque(false);
        encryptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encryptBtnActionPerformed(evt);
            }
        });
        backgroundPnl.add(encryptBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        decryptLbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        decryptLbl.setText("Enter A Message To Decyrpt:");
        backgroundPnl.add(decryptLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        backgroundPnl.add(decryptTxtFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 380, -1));

        errorLbl.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        errorLbl.setForeground(new java.awt.Color(255, 0, 0));
        errorLbl.setText("ERROR: ENTER MESSAGE LESS THAN 36 CHARACTERS");
        backgroundPnl.add(errorLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        getContentPane().add(backgroundPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void encryptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encryptBtnActionPerformed
        //Variables
        String userMessage = encryptTxtFeild.getText();
        char userMessageChar = 'a';
        int userMessageEncrypt = 0;
        String userMessageEncrypted = "";
        errorLbl.setVisible(false);
        
        if (userMessage.length() <= 31){
            
            for (int i = userMessage.length() - 1; i >= 0; i--){
                userMessageChar = userMessage.charAt(i);
                userMessageEncrypt = (int)userMessageChar;
                userMessageEncrypt = userMessageEncrypt + 4;
                userMessageChar = (char)userMessageEncrypt; 
                userMessageEncrypted = userMessageEncrypted + Character.toString(userMessageChar); 
            }
            
            encryptOutPutTxtFeild.setText(userMessageEncrypted);
            
        }
        else{
            errorLbl.setVisible(true);
        }
    }//GEN-LAST:event_encryptBtnActionPerformed

    private void decryptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptBtnActionPerformed
        String userMessage = decryptTxtFeild.getText();
        char userMessageChar = 'a';
        int userMessageDecrypt = 0;
        String userMessageDecrypted = "";
        errorLbl.setVisible(false);
        
        if (userMessage.length() <= 36){
            
            
            
            for (int i = userMessage.length() - 1; i >= 0; i--){
                userMessageChar = userMessage.charAt(i);
                userMessageDecrypt = (int)userMessageChar;
                userMessageDecrypt = userMessageDecrypt - 4;
                userMessageChar = (char)userMessageDecrypt; 
                userMessageDecrypted = userMessageDecrypted + Character.toString(userMessageChar);
                
            }
            
            userMessageDecrypted.trim();
            decryptOutPutTxtFeild.setText(userMessageDecrypted);
        }
        else{
            errorLbl.setVisible(true);
            
        }
    }//GEN-LAST:event_decryptBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(encryptAndDecrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(encryptAndDecrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(encryptAndDecrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(encryptAndDecrypt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new encryptAndDecrypt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPnl;
    private javax.swing.JButton decryptBtn;
    private javax.swing.JLabel decryptLbl;
    private javax.swing.JLabel decryptOutPutLbl;
    private javax.swing.JTextField decryptOutPutTxtFeild;
    private javax.swing.JTextField decryptTxtFeild;
    private javax.swing.JButton encryptBtn;
    private javax.swing.JLabel encryptLbl;
    private javax.swing.JTextField encryptOutPutTxtFeild;
    private javax.swing.JLabel encryptOutputLbl;
    private javax.swing.JTextField encryptTxtFeild;
    private javax.swing.JLabel errorLbl;
    private javax.swing.JLabel titleLbl;
    // End of variables declaration//GEN-END:variables
}
